[workspace]
channels = ["https://repo.prefix.dev/brads-forge", "conda-forge"]
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]

[tasks.code]
cmd = "code ."

[tasks.zed]
cmd = "zed ."

[dependencies]
deno = ">=2.7.14,<2.8"
rattler-build = ">=0.64.1,<0.65"
