# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1
package:
  name: dprint
  version: 0.47.6
context:
  rawVersion: 0.47.6
source:
  - if: target_platform == "osx-arm64"
    then:
      sha256: 4f33c24141a19638ab045fe5e95654ff0ef8db29949e145d28ea3cc5b088a042
      url: >-
        https://github.com/dprint/dprint/releases/download/0.47.6/dprint-aarch64-apple-darwin.zip
  - if: target_platform == "linux-aarch64"
    then:
      sha256: a89fde49d786dc3c8e1fd5758359ade248addab1e2ded24a782ec8e738231153
      url: >-
        https://github.com/dprint/dprint/releases/download/0.47.6/dprint-aarch64-unknown-linux-gnu.zip
  - if: target_platform == "unknown-aarch64"
    then:
      sha256: 221aaecc5e71d73591b226377064a33b4d15a5aae6788ef11c99a4da540a095d
      url: >-
        https://github.com/dprint/dprint/releases/download/0.47.6/dprint-aarch64-unknown-linux-musl.zip
  - if: target_platform == "linux-riscv64"
    then:
      sha256: c335c3aff2812ca1f640af10f13a2d94cc6d414814dc8038e7412aacc3065ea0
      url: >-
        https://github.com/dprint/dprint/releases/download/0.47.6/dprint-riscv64gc-unknown-linux-gnu.zip
  - if: target_platform == "osx-64"
    then:
      sha256: b54950d447e0d17fcc2732bf99928503deb39b5b764e5b33995449bf6059c857
      url: >-
        https://github.com/dprint/dprint/releases/download/0.47.6/dprint-x86_64-apple-darwin.zip
  - if: target_platform == "win-64"
    then:
      sha256: 0c9abe671652b8da61227b92b0bc038b1e938367fa3d7a9fa3ba523d515d4a9a
      url: >-
        https://github.com/dprint/dprint/releases/download/0.47.6/dprint-x86_64-pc-windows-msvc.zip
  - if: target_platform == "linux-64"
    then:
      sha256: cf572c3207ccf870e6f670b1088c843a9b77930e00e8a34239b0dda4a856a237
      url: >-
        https://github.com/dprint/dprint/releases/download/0.47.6/dprint-x86_64-unknown-linux-gnu.zip
  - if: target_platform == "unknown-64"
    then:
      sha256: ab0cd8c86d224b51371bb0a5c50418376b153a643d024022977e4d72cad529e6
      url: >-
        https://github.com/dprint/dprint/releases/download/0.47.6/dprint-x86_64-unknown-linux-musl.zip
requirements:
  build:
    - deno=2.1.2
build:
  number: 0
  dynamic_linking:
    binary_relocation: false
    overdepending_behavior: error
    overlinking_behavior: error
  script:
    - if: build_platform | split('-') | first == win
      then: >-
        deno run -A %RECIPE_DIR%/bundled-recipe.ts execute --build
        --build-platform ${{ build_platform }} --target-platform ${{
        target_platform }} --pkg-version-raw ${{ rawVersion }}
      else: >-
        deno run -A $RECIPE_DIR/bundled-recipe.ts execute --build
        --build-platform ${{ build_platform }} --target-platform ${{
        target_platform }} --pkg-version-raw ${{ rawVersion }}
  skip: >-
    target_platform != "osx-arm64" and target_platform != "linux-aarch64" and
    target_platform != "unknown-aarch64" and target_platform != "linux-riscv64"
    and target_platform != "osx-64" and target_platform != "win-64" and
    target_platform != "linux-64" and target_platform != "unknown-64"
tests:
  - script: >-
      deno run -A ./info/recipe/bundled-recipe.ts execute --test
      --build-platform ${{ build_platform }} --target-platform ${{
      target_platform }} --pkg-version-raw ${{ rawVersion }}
    requirements:
      build:
        - deno=2.1.2
about:
  summary: Pluggable and configurable code formatting platform written in Rust.
  description: >
    # dprint


    [![CI](https://github.com/dprint/dprint/workflows/CI/badge.svg)](https://github.com/dprint/dprint/actions?query=workflow%3ACI)

    [![Homebrew](https://img.shields.io/badge/dynamic/json.svg?url=https://formulae.brew.sh/api/formula/dprint.json&query=$.versions.stable&label=homebrew)](https://formulae.brew.sh/formula/dprint)


    Monorepo for dprint—a pluggable and configurable code formatting platform.


    ## Links


    - [Overview](https://dprint.dev/overview)

    - [Getting Started](https://dprint.dev/install)

    - [Playground](https://dprint.dev/playground)


    ## Plugins


    See https://dprint.dev/plugins/


    Repos:


    -
    [dprint-plugin-typescript](https://github.com/dprint/dprint-plugin-typescript)
    - TypeScript/JavaScript code formatter.

    - [dprint-plugin-json](https://github.com/dprint/dprint-plugin-json) -
    JSON/JSONC code formatter.

    - [dprint-plugin-markdown](https://github.com/dprint/dprint-plugin-markdown)
    - Markdown code formatter.

    - [dprint-plugin-toml](https://github.com/dprint/dprint-plugin-toml) - TOML
    code formatter.

    - [dprint-plugin-jupyter](https://github.com/dprint/dprint-plugin-jupyter) -
    Jupyter notebook code block formatter.

    -
    [dprint-plugin-dockerfile](https://github.com/dprint/dprint-plugin-dockerfile)
    - Dockerfile code formatter.

    - [dprint-plugin-biome](https://github.com/dprint/dprint-plugin-biome) -
    Biome (JS/TS) wrapper plugin.

    - [dprint-plugin-prettier](https://github.com/dprint/dprint-plugin-prettier)
    - Prettier wrapper plugin.

    - [dprint-plugin-roslyn](https://github.com/dprint/dprint-plugin-roslyn) -
    Roslyn (C#/VB) wrapper plugin.

    - [dprint-plugin-ruff](https://github.com/dprint/dprint-plugin-ruff) - Ruff
    (Python) wrapper plugin.

    - [dprint-plugin-exec](https://github.com/dprint/dprint-plugin-exec) -
    Formats code with any CLI executable.

    - [Malva](https://github.com/g-plane/malva) - CSS/SCSS/Sass/Less formatter

    - [markup_fmt](https://github.com/g-plane/markup_fmt) - HTML, Vue, Svelte,
    Astro, Angular, Jinja, Twig, Nunjucks, and Vento formatter.

    - [pretty_graphql](https://github.com/g-plane/pretty_graphql) - GraphQL
    formatter.

    - [pretty_yaml](https://github.com/g-plane/pretty_yaml) - YAML formatter.


    ## Notes


    I do a lot of this development in my spare time. Please consider
    [sponsoring](https://dprint.dev/sponsor) if you are a commercial company
    using this.
  homepage: 'https://dprint.dev/'
  repository: 'https://github.com/dprint/dprint'
  license: MIT
