# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1
package:
  name: lefthook
  version: v1.9.0
source:
  - if: target_platform == "linux-arm64"
    then:
      sha256: 5d0eea971c4c28cc0e9dee4cb30dd1b55cb810a8330999a747a7c3545707cd2e
      url: >-
        https://github.com/evilmartians/lefthook/releases/download/v1.9.0/lefthook_1.9.0_Linux_arm64.gz
  - if: target_platform == "linux-64"
    then:
      sha256: 18fba84f176f4e44dccc4baadc764f74717936216fc2c2c23a765e9399a21ea1
      url: >-
        https://github.com/evilmartians/lefthook/releases/download/v1.9.0/lefthook_1.9.0_Linux_x86_64.gz
  - if: target_platform == "osx-arm64"
    then:
      sha256: adad7871db0bced264fc1e669eaf836bc1e8c82688af65f3ab1a5b4e6a9c3b3c
      url: >-
        https://github.com/evilmartians/lefthook/releases/download/v1.9.0/lefthook_1.9.0_MacOS_arm64.gz
  - if: target_platform == "osx-64"
    then:
      sha256: 7514e3baf1f60ade4b52727896349b2e01e274baac8644e5a2a0cab267d667ec
      url: >-
        https://github.com/evilmartians/lefthook/releases/download/v1.9.0/lefthook_1.9.0_MacOS_x86_64.gz
  - if: target_platform == "win-arm64"
    then:
      sha256: e54f5511e74914d21983e35ea2dbaeb31219f839e6c6fc340fa593c1f85ed73f
      url: >-
        https://github.com/evilmartians/lefthook/releases/download/v1.9.0/lefthook_1.9.0_Windows_arm64.gz
  - if: target_platform == "win-32"
    then:
      sha256: 4c025bc28509b2b3718f160a3dcd9ddcfa3ece6a00ec58ea3d19cb57435a096c
      url: >-
        https://github.com/evilmartians/lefthook/releases/download/v1.9.0/lefthook_1.9.0_Windows_i386.gz
  - if: target_platform == "win-64"
    then:
      sha256: 1b595d18d3908bc57570de2b5ed586879871a3491ce3995edc88a5de813b4938
      url: >-
        https://github.com/evilmartians/lefthook/releases/download/v1.9.0/lefthook_1.9.0_Windows_x86_64.gz
requirements:
  build:
    - deno=2.1.2
build:
  number: 0
  dynamic_linking:
    binary_relocation: false
    overdepending_behavior: error
    overlinking_behavior: error
  script:
    - if: build_platform | split('-') | first == win
      then: >-
        deno run -A %RECIPE_DIR%/bundled-recipe.ts execute --build
        --build-platform ${{ build_platform }} --target-platform ${{
        target_platform }}
      else: >-
        deno run -A $RECIPE_DIR/bundled-recipe.ts execute --build
        --build-platform ${{ build_platform }} --target-platform ${{
        target_platform }}
  skip: >-
    target_platform != "linux-arm64" and target_platform != "linux-64" and
    target_platform != "osx-arm64" and target_platform != "osx-64" and
    target_platform != "win-arm64" and target_platform != "win-32" and
    target_platform != "win-64"
tests:
  - script: >-
      deno run -A ./info/recipe/bundled-recipe.ts execute --test
      --build-platform ${{ build_platform }} --target-platform ${{
      target_platform }}
    requirements:
      build:
        - deno=2.1.2
about:
  summary: Fast and powerful Git hooks manager for any type of projects.
  description: >-
    https://raw.githubusercontent.com/evilmartians/lefthook/refs/heads/master/README.md
  homepage: 'https://github.com/evilmartians/lefthook'
  license_url: >-
    https://raw.githubusercontent.com/evilmartians/lefthook/refs/heads/master/LICENSE
